In [3]:
import pandas as pd

# **Q1. Pandas version**

You can get the version information using the __version__ field:

In [4]:
pd.__version__

'2.1.4'

In [5]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'
df = pd.read_csv(url)


# **Q2. Records count**
How many records are in the dataset?

12
1000
2160
12160


In [7]:
print(df.shape[0])


2160


# **Q3. Laptop brands**
How many laptop brands are presented in the dataset?

12
27
28
2160

In [9]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [10]:
print(df['Brand'].nunique())


27


# **Q4. Missing values**
How many columns in the dataset have missing values?

0
1
2
3

In [11]:
print(df.isnull().any().sum())


3


# **Q5. Maximum final price**
What's the maximum final price of Dell notebooks in the dataset?

869
3691
3849
3936

In [13]:
dell_df = df[df['Brand'] == 'Dell']



In [14]:
dell_df

Laptop       Status Brand  \
161   Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...          New  Dell   
271   Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...          New  Dell   
281   Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...          New  Dell   
319   Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...          New  Dell   
328   Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...          New  Dell   
...                                                 ...          ...   ...   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
1844  Dell Vostro 5301 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1845  Dell Vostro 5502 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1846  Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512G...  Refurbished  Dell   
1847  Dell XPS 7390 Intel Core i7-10510U/16GB/512GB ...  Refurbished  Dell   

         Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
161     Vostro  Intel Core i3    8      256          SSD  NaN    15.6    No   
271     Vostro  Intel Core i5    8      256          SSD  NaN    15.6    No   
281     Vostro  Intel Core i7   16      512          SSD  NaN    15.6    No   
319   Latitude  Intel Core i5    8      256          SSD  NaN    15.6    No   
328     Vostro  Intel Core i5   16      512          SSD  NaN    15.6    No   
...        ...            ...  ...      ...          ...  ...     ...   ...   
1843    Vostro  Intel Core i5    8      256          SSD  NaN    13.3    No   
1844    Vostro  Intel Core i5    8      512          SSD  NaN    13.3    No   
1845    Vostro  Intel Core i5    8      512          SSD  NaN    15.6    No   
1846       XPS  Intel Core i5    8      512          SSD  NaN    13.4    No   
1847       XPS  Intel Core i7   16      512          SSD  NaN    13.3    No   

      Final Price  
161        599.00  
271        690.15  
281        889.00  
319        789.00  
328        869.00  
...           ...  
1843       420.74  
1844       511.59  
1845       549.93  
1846       699.00  
1847      1086.88  

[84 rows x 12 columns]

In [20]:
dell_df['Final Price'].max()


3936.0

# **Q6. Median value of Screenn**
Find the median value of Screen column in the dataset.

Next, calculate the most frequent value of the same Screen column.

Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

Now, calculate the median value of Screen once again.

Has it changed?

In [22]:
df['Screen'].median()

15.6

In [23]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [26]:
print(df['Screen'].isnull().sum())


4


In [29]:
df_missing = df['Screen'].isnull()

In [32]:
print(df_missing[df_missing == True])


624     True
1430    True
1503    True
1548    True
Name: Screen, dtype: bool


In [39]:
most_frequent_screen = df['Screen'].mode()[0]
df['Screen'].fillna(most_frequent_screen, inplace=True)
new_median_screen = df['Screen'].median()
print(new_median_screen)


15.6


In [40]:
df_missing = df['Screen'].isnull()

In [41]:
print(df_missing[df_missing == True])

Series([], Name: Screen, dtype: bool)


No changes

# **Q7. Sum of weights**
Select all the "Innjoo" laptops from the dataset.

Select only columns RAM, Storage, Screen.

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Compute the inverse of XTX.

Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

In [42]:
innjoo_df = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]
print(innjoo_df)


      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1


In [44]:
X = innjoo_df.values


In [45]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [48]:
XTX = X.T.dot(X)


In [49]:
import numpy as np

XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)


[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [50]:
import numpy as np
y = np.array([1100, 1300, 800, 900, 1000, 1100])


In [51]:
w = (XTX_inv.dot(X.T)).dot(y)
print(w)
print(w.sum())


[45.58076606  0.42783519 45.29127938]
91.2998806299555
